### ISSUE TITLE
django shell with ipython not working on master (even in ignore mode)

### ISSUE THREAD

**Issue by benjaminrigaud** [LPgenerator/django-mmc#6]
```python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/beno/projects/django-mmc/mmc/mixins.py", line 115, in execute
    self.__mmc_execute(*args, **options)
  File "/home/beno/projects/django-mmc/mmc/mixins.py", line 99, in __mmc_execute
    self.__mmc_run(*args, **options)
  File "/home/beno/projects/django-mmc/mmc/mixins.py", line 93, in __mmc_run
    self._no_monkey.execute(self, *args, **options)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 77, in handle_noargs
    self.run_shell(shell=interface)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 62, in run_shell
    return getattr(self, shell)()
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 45, in ipython
    ip()
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 39, in _ipython
    start_ipython(argv=[])
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 332, in initialize
    self.init_shell()
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 348, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/config/configurable.py", line 354, in instance
    inst = cls(*args, **kwargs)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 328, in __init__
    **kwargs
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 499, in __init__
    self.init_io()
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 663, in init_io
    io.stdout = io.IOStream(sys.stdout)
  File "/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/IPython/utils/io.py", line 41, in __init__
    raise ValueError("fallback required, but not specified")
ValueError: fallback required, but not specified

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

Error: fallback required, but not specified
```

**Comment by gotlium** [comment]
1. py version? 
2. os?
3. cmd
4. dj version

give me more info

**Comment by benjaminrigaud** [comment]
Did a clone of the repo inside a virtualenv with Python 2.7.6 under Ubuntu 14.04
Installed Django==1.7.4 and ipython==2.4.1

The command is:

./manage.py shell

It seems ipython doesn't like the replaced stdin

**Comment by gotlium** [comment]
mkvirtualenv dj-mmc-test
    pip install Django==1.7.4 ipython==2.4.1 django-mmc
    django-admin startproject immctst
    cd immctst
    mkdir apps
    cat > apps/__init__.py << END
    from mmc.mixins import inject_management
    inject_management()
    END
    cd apps
    django-admin startapp tst
    cd ../
    sed -i 's/django.contrib.staticfiles/apps.tst/g' immctst/settings.py
    ./manage.py shell
    [MMC] no such table: mmc_mmcscript
    /Users/gotlium/.virtualenvs/dj-mmc-test/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py:63: RuntimeWarning: SQLite received a naive datetime (2015-02-12 11:11:51.957883) while time zone support is active.
      RuntimeWarning)
    
    Python 2.7.8 (default, Oct 16 2014, 05:18:45) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 2.3.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: 


seems it works

**Comment by gotlium** [comment]
I see system IPython 2.3.0 found. I'll re-test it.

**Comment by benjaminrigaud** [comment]
A little clarification: it is with django-mmc master clone (not the 1.4 you are installing with pip)

**Comment by gotlium** [comment]
On master we are reading StdOut and save results into database.

**Comment by benjaminrigaud** [comment]
Exactly:

https://github.com/LPgenerator/django-mmc/blob/f30cda0dbb08f021854936facc4702f5136d572c/mmc/mixins.py#L57

And ipython can't handle it.

**Comment by gotlium** [comment]
I'm understand. Just a moment. It fixed at my local repo

**Comment by gotlium** [comment]
Can you check now?

**Comment by benjaminrigaud** [comment]
Ok, new error:

AttributeError: 'StdOut' object has no attribute 'fileno'

**Comment by gotlium** [comment]
Can you show traceback?

**Comment by benjaminrigaud** [comment]
There is another library in the way (prompt_toolkit):

```python
AttributeError                            Traceback (most recent call last)
/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/prompt_toolkit-0.21-py2.7.egg/prompt_toolkit/contrib/ipython.pyc in raw_input(self, prompt)
    123         print('')
    124         try:
--> 125             string = self._cli.read_input(on_exit=AbortAction.RAISE_EXCEPTION).text
    126 
    127             # In case of multiline input, make sure to append a newline to the input,

/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/prompt_toolkit-0.21-py2.7.egg/prompt_toolkit/__init__.pyc in read_input(self, initial_value, initial_input_mode, on_abort, on_exit)
    249                 self.renderer.request_absolute_cursor_position()
    250 
--> 251                 self._redraw()
    252 
    253                 with (DummyContext() if sys.platform == 'win32' else

/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/prompt_toolkit-0.21-py2.7.egg/prompt_toolkit/__init__.pyc in _redraw(self)
    179         (From other threads, or if unsure, use `request_redraw`.)
    180         """
--> 181         self.renderer.render(self)
    182 
    183     def run_in_executor(self, callback):

/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/prompt_toolkit-0.21-py2.7.egg/prompt_toolkit/renderer.pyc in render(self, cli)
    468 
    469         # Create screen and write layout to it.
--> 470         screen = Screen(size=output.get_size())
    471 
    472         height = self._last_screen.current_height if self._last_screen else 0

/home/beno/venvs/django-mmc/local/lib/python2.7/site-packages/prompt_toolkit-0.21-py2.7.egg/prompt_toolkit/terminal/vt100_output.pyc in get_size(self)
     47     def get_size(self):
     48         from ..renderer import Size
---> 49         rows, columns = _get_size(self.stdout.fileno())
     50         return Size(rows=rows, columns=columns)
     51 

AttributeError: 'StdOut' object has no attribute 'fileno'
```

I'll try without it.

**Comment by benjaminrigaud** [comment]
Without prompt_toolkit, ipython launches but the prompt is broken:

Strange characters and most interactive features are KO.

Maybe we could make a proxy StdOut class (inheriting from file) and passing all calls to the true stdout (+ appending on write) 

```python
class StdOut(file):

    def __init__(self, stdout):
        self.data = []
        self.stdout = stdout

    def write(self, message):
        self.data.append(message)

        self.stdout.write(message)

    ... for each method ...
```

I have to eat now, i'll be back in 1h.

**Comment by gotlium** [comment]
Check now again

**Comment by benjaminrigaud** [comment]
Same pb. Back in 1h.

**Comment by gotlium** [comment]
Stdout functionality now disabled for IPython

**Comment by benjaminrigaud** [comment]
I tried your fix: It doesn't work :/

__IPYTHON__ isn't defined at the start of the command (I suppose ipython isn't launched yet)

**Comment by gotlium** [comment]
any ideas how we can fix it?

**Comment by benjaminrigaud** [comment]
Not yet, I'll do some more tests tomorrow.

**Comment by gotlium** [comment]
Ok, thanks:)

**Comment by gotlium** [comment]
version 1.5 was released. stdout capture now is optionally and can be disabled. maybe someday this functionality will be enabled by default.
